services:
  database:
    hostname: fisk_db 
    build: 
      dockerfile: database.DockerFile
      context: .
    environment:
      MYSQL_DB: trefiskmasar_db
      MYSQL_ROOT_PASSWORD: Fiskarna78$
      MYSQL_ROOT_USER: root
    volumes:
      - db_backup:/var/lib/mysql

  server: 
    build: 
      dockerfile: serverHost.DockerFile
      context: .
    volumes: 
      - ./www-root:/var/www/html
    depends_on:
      - database 
    ports:
      - "5150:80"

volumes:
  db_backup: {}

